# After each sign in, update credentials refreshed at time.
#
# `record.class.otp_credentials_refresh` is generated by `Devise::Models.config`
# on any model that includes `:otp_authenticatable`, so `defined?` is always
# truthy for those models. Guard on the *value* instead — when the setting is
# `false` (disabled), skip the assignment so we don't raise `TypeError` on
# `Time.now + false`.
Warden::Manager.after_set_user except: :fetch do |record, warden, options|
  refresh_in = record.class.otp_credentials_refresh if record.class.respond_to?(:otp_credentials_refresh)
  warden.session(options[:scope])["credentials_refreshed_at"] = Time.now + refresh_in if refresh_in
end
